-- EXERCÍCIO 3: CRIAR A TABELA CATEGORIES
-- A TABELA DEVE CONTER:
-- ID (CHAVE PRIMÁRIA)
-- NAME
-- DICA: UTILIZE PRIMARY KEY E AUTO_INCREMENT
use DB_VITORIA_B;

CREATE TABLE CATEGORIES(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50)
    );
 
-- EXERCÍCIO 4: CRIAR A TABELA FOODS
-- A TABELA DEVE CONTER:
-- ID (CHAVE PRIMÁRIA)
-- NAME
-- PRICE
-- CATEGORY_ID (CHAVE ESTRANGEIRA)
-- DICA: UTILIZE FOREIGN KEY PARA RELACIONAR COM CATEGORIES
 
 CREATE TABLE FOODS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30),
    PRICE  DECIMAL(10,2) NOT NULL,
    ID_CATEGORIES INT,
	CONSTRAINT FK_CATEGORIES FOREIGN KEY (ID_CATEGORIES) references CATEGORIES(ID)
);
-- EXERCÍCIO 5: INSERIR PELO MENOS 4 REGISTROS NA TABELA CATEGORIES
-- EXEMPLOS DE CATEGORIAS: FAST FOOD, DESSERT, DRINK, VEGETARIAN
-- DICA: UTILIZE INSERT INTO
 
 INSERT INTO CATEGORIES()
 VALUE(NULL,'FRUITS & VEGETABLES'),
 (NULL,'SWEETS & DESSERTS'),
 (NULL,'DRINKS & BEVERAGES'),
 (NULL,'GLUTEN FREE');
 
-- EXERCÍCIO 6: INSERIR PELO MENOS 10 REGISTROS NA TABELA FOODS
-- DICA: O CATEGORY_ID DEVE EXISTIR NA TABELA CATEGORIES
 
 INSERT INTO FOODS ()
 VALUES
 (NULL,'POTATO','7','1'),
 (NULL,'SODA','3','3'),
 (NULL,'BLUEBERRYS','12','1'),
 (NULL,'GLUTEN FREE PASTA','10','4'),
 (NULL,'CHOCOLATE','7.5','2'),
 (NULL,'LIME JUICE','10','3'),
 (NULL,'KALE','3','1'),
 (NULL,'GLUTEN FREE BREAD','6.5','4'),
 (NULL,'MACAROONS','3.5','2'),
 (NULL,'WHISKEY','7','3');
 
-- EXERCÍCIO 7: LISTAR TODAS AS COMIDAS
SELECT * FROM DB_VITORIA_B.FOODS;
 
-- EXERCÍCIO 8: LISTAR APENAS AS COMIDAS DA CATEGORIA FAST FOOD
-- DICA: UTILIZE WHERE FILTRANDO PELO NOME DA CATEGORIA
 
select * FROM DB_VITORIA_B.FOODS
WHERE ID_CATEGORIES = '1';

-- EXERCÍCIO 9: ORDENAR AS COMIDAS PELO PREÇO DO MAIOR PARA O MENOR
-- DICA: UTILIZE ORDER BY DESC
 
 Select * from DB_VITORIA_B.FOODS
 ORDER BY PRICE DESC;
 
-- EXERCÍCIO 10: APAGAR UMA COMIDA ESPECÍFICA PELO NOME
-- DICA: UTILIZE DELETE FROM COM WHERE
 SET SQL_SAFE_UPDATES = 0;
 DELETE FROM DB_VITORIA_B.FOODS
 where name = 'POTATO';
 
-- EXERCÍCIO 11: APAGAR TODAS AS COMIDAS COM PREÇO MENOR QUE 10
-- DICA: UTILIZE DELETE + WHERE COM OPERADOR <
 delete from DB_VITORIA_B.FOODS 
	where PRICE < 10;
 
-- EXERCÍCIO 12: CONSULTAR TODAS AS COMIDAS APÓS AS EXCLUSÕES
-- DICA: UTILIZE SELECT *

Select * from DB_VITORIA_B.FOODS;
