-- 13
select top 3 *
from AUTORES
order by DATA_NASCIMENTO ASC;

-- 14
select * from NOVELAS
where TITULO LIKE 'A%';

-- 15
-- EXERCÍCIO 15
-- LISTE NOVELAS EXIBIDAS EM DETERMINADOS HORÁRIOS
-- DICA: IN
select * from NOVELAS
where HORARIO_EXIBICAO IN ('20:00', '21:00');

--16
--EXERCÍCIO 16
-- MOSTRE CAPÍTULOS EXIBIDOS ENTRE DUAS DATAS
-- DICA: BETWEEN 
select * from CAPITULOS
where DATA_EXIBICAO between '2024-01-01' and '2024-12-31';

-- EXERCÍCIO 17
-- MOSTRE A MENOR E A MAIOR AUDIÊNCIA REGISTRADA
-- DICA: MIN E MAX
select MIN(PONTUACAO) as menor_audiencia, MAX(PONTUACAO) as maior_audiencia
from AUDIENCIAS;

-- EXERCÍCIO 18
-- MOSTRE A AUDIÊNCIA MÉDIA POR NOVELA
-- DICA: JOIN + GROUP BY-- EXERCÍCIO 18
-- MOSTRE A AUDIÊNCIA MÉDIA POR NOVELA

select N.TITULO, AVG(A.PONTUACAO) AS AUDIENCIA_MEDIA
from  NOVELAS N
join  CAPITULOS C ON N.ID = C.NOVELA_ID
join  AUDIENCIAS A ON C.ID = A.CAPITULO_ID
GROUP BY N.TITULO;

-- EXERCÍCIO 19
-- LISTE NOVELAS COM AUDIÊNCIA MÉDIA ACIMA DE UM VALOR
-- DICA: HAVING
select N.TITULO, AVG(A.PONTUACAO) AS Audi_MEDIA
from  NOVELAS N
join  CAPITULOS C ON N.ID = C.NOVELA_ID
join  AUDIENCIAS A ON C.ID = A.CAPITULO_ID
GROUP BY N.TITULO
having AVG(A.PONTUACAO) > 30.0;

-- EXERCÍCIO 20
-- MOSTRE A QUANTIDADE DE PERSONAGENS POR NOVELA
-- DICA: COUNT
select N.TITULO, COUNT(P.ID) AS QTD_PERSONA
from NOVELAS N
join PERSONAGENS P ON N.ID = P.NOVELA_ID
GROUP BY N.TITULO;

-- EXERCÍCIO 21
-- LISTE ATORES QUE ATUARAM EM MAIS DE UMA NOVELA
-- DICA: GROUP BY + HAVING
select A.NOME, COUNT( P.NOVELA_ID) AS QTD_NOVELAS
from ATORES A
join PERSONAGENS P ON A.ID = P.ATOR_ID
GROUP BY A.NOME
having COUNT( P.NOVELA_ID) > 1;

-- EXERCÍCIO 22
-- MOSTRE NOVELAS QUE POSSUEM MAIS PERSONAGENS
-- DO QUE A MÉDIA GERAL
-- DICA: SUBQUERY
select N.TITULO, COUNT(P.ID) AS QTD_PERSONAGENS
from NOVELAS N
join PERSONAGENS P ON N.ID = P.NOVELA_ID
GROUP BY N.TITULO

having COUNT(P.ID) > (select AVG(QTD) 
    from (select COUNT(ID) AS QTD from PERSONAGENS 
    group by NOVELA_ID
    ) AS subquery
);

 
-- EXERCÍCIO 23
-- LISTE CAPÍTULOS COM AUDIÊNCIA ACIMA DA MÉDIA
-- DICA: SUBQUERY + WHERE
select C.NUMERO_CAPITULO, A.PONTUACAO
from CAPITULOS C
join AUDIENCIAS A ON C.ID = A.CAPITULO_ID
where A.PONTUACAO > (select AVG(PONTUACAO) from AUDIENCIAS);

 
-- EXERCÍCIO 24
-- MOSTRE OS 3 CAPÍTULOS COM MAIOR AUDIÊNCIA
-- DICA: TOP + ORDER BY DESC
select top 3 C.NUMERO_CAPITULO, A.PONTUACAO
from CAPITULOS C
join AUDIENCIAS A ON C.ID = A.CAPITULO_ID
order by A.PONTUACAO DESC

-- EXERCÍCIO 25 
-- MOSTRE:
-- NOME DO AUTOR
-- TÍTULO DA NOVELA
-- TOTAL DE CAPÍTULOS
-- MAIOR AUDIÊNCIA
-- DICA: JOIN + GROUP BY + FUNÇÕES DE AGREGAÇÃO
select A.NOME as AUTOR, N.TITULO as NOVELA, 
COUNT(C.ID) as TOTAL_CAPITULOS, 
MAX(AU.PONTUACAO) as MAIOR_AUDIENCIA
from AUTORES A
join NOVELAS N ON A.ID = N.AUTOR_ID
join CAPITULOS C ON N.ID = C.NOVELA_ID
join AUDIENCIAS AU ON C.ID = AU.CAPITULO_ID
group by A.NOME, N.TITULO
order by MAIOR_AUDIENCIA DESC;